### ISSUE TITLE
Calculate Reverse Alt-IDs "on the fly"?

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#10]
I was thinking if we couldn't simplify the Reverse-Alt-ID topic by calculating the AltIDs on-the-fly.

```
<?php

require_once __DIR__ . '/includes/oidplus.inc.php';

OIDplus::init(true);

$alt_ids = array();
$rev_lookup = array();

$res = OIDplus::db()->query("select id from ###objects");
while ($row = $res->fetch_array()) {
        $origin = $row['id'];
        $obj = OIDplusObject::parse($origin);
        if (!$obj) continue; // e.g. if plugin is disabled
        $ary = $obj->getAltIds();
        foreach ($ary as $a) {
                $alternative = $a->getNamespace() . ':' . $a->getId();

                if (!isset($alt_ids[$origin])) $alt_ids[$origin] = array();
                $alt_ids[$origin][] = $alternative;

                if (!isset($rev_lookup[$alternative])) $rev_lookup[$alternative] = array();
                $rev_lookup[$alternative][] = $origin;
        }
}

print_r($alt_ids);
print_r($rev_lookup);
```

How to use it in your plugin:

```
        public static function test() {
                $alt_ids = array();
                $rev_lookup = array();

                $res = OIDplus::db()->query("select id from ###objects");
                while ($row = $res->fetch_array()) {
                        $obj = OIDplusObject::parse($row['id']);
                        if (!$obj) continue; // e.g. if plugin is disabled
                        $ary = $obj->getAltIds();
                        foreach ($ary as $a) {
                                $origin = $obj->nodeId(true);
                                $alternative = $a->getNamespace() . ':' . $a->getId();

                                if (!isset($alt_ids[$origin])) $alt_ids[$origin] = array();
                                $alt_ids[$origin][] = $alternative;

                                if (!isset($rev_lookup[$alternative])) $rev_lookup[$alternative] = array();
                                $rev_lookup[$alternative][] = $origin;
                        }
                }
                return array($alt_ids, $rev_lookup);
        }

       public function getAlternativesForQuery($id) {
                list($alt_ids, $rev_lookup) = self::test();
                if (!isset($rev_lookup[$id])) return array();
                return $rev_lookup[$id];
        }

```

Performance is actually not bad... on my system:
867 objects in 0.60397 seconds

Ideas how to improve performance:
- We could also cache it using a `serialize()` file. (folder userdata/cache/*.ser)
- If we call this code only on demand, e.g. if an object was not found (404) and we need to find an alternative.

But I feel a bit bad because this basically "destroys" your plugin in its current shape (or at least the database / caching part of it)

**Comment by wehowski** [comment]
Hallo Daniel, 
danke! Ich hab nun folgende Lösung: https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L49

**Comment by danielmarschall** [comment]
Hallo Till,
bei dir wird aber die Datenbank verwendet,
wovon ich persönlich eher wegkommen würde ( aufgrund #1 und #2 ) ,
da die komplette Erstellung der Lookup-Tabelle ohne Cache ist bereits sehr schnell,
und wenn man einen serialized Cache macht, der vorzugsweise als Cronjob sich erneuert, dann ist es quasi Echtzeit

**Comment by wehowski** [comment]
Achso. Mir war nicht klar das $res = OIDplus::db()->query("select id from ###objects"); gecached wird?
Kann es denn beim Einlesen der KOMPLETTEN Objects  nicht zu memory issues kommen, wenn z.B. sagen wir ein paar Millionen Einträge vorhanden sind?

**Comment by danielmarschall** [comment]
Hallo Till, Entschuldigung, meine Antwort war mehrdeutig. :-) 

Die `query()` wird nicht gecached, nein. Mein Code oben wird derzeit gar nicht optimiert und deswegen sehr langsam.
Meine Idee ist, diese Prozedur (die ca. 2 Sekunden braucht) in in eine Datei zwischenzuspeichern und die Datei alle 60 Minuten neu zu schreiben, oder neu zu schreiben, wenn ein Objekt angelegt oder gelöscht wurde. Irgendwie sowas in der Art.
Mir persönlich wäre es lieb wenn die Datenbanktabelle `alt_id` ersetzt und stattdessen die zwei Lookup-Arrays ("forward" `$alt_ids` und "reverse" `$rev_lookup`) verwendet.

PHP ist sehr speicherhungrig, aber ich denke nicht, dass es Speicherprobleme mit `$alt_ids` und `$rev_lookup` geben könnte. Wenn man wirklich millionen von Objekten hätte, dann würde OIDplus mit sehr hoher Wahrscheinlichkeit an anderen Stellen (z.B. der Sortierungen) zusammenbrechen.

**Comment by danielmarschall** [comment]
@wehowski Hallo Till,
wäre es möglich, dass du dein Plugin so umschreibst, dass wir eine zentrale Funktion haben (genauso wie mein `test()` oben), die zurückgibt `array($alt_ids, $rev_lookup)` (also einmal ein "forward" lookup array `$alt_ids` und einmal ein "reverse" lookup array `$rev_lookup`) ? Wir können dann ja immer noch entscheiden, ob diese Funktion dann die Daten aus einer Datenbanktabelle, aus einer Cache-JSON-Datei oder Live berechnet, das wäre dann ja ein Implementierungsdetail. Was meinst du?

**Comment by wehowski** [comment]
Hallo Daniel,
ja, gute Idee! Ich komme allerdings erst am Dienstag oder Mittwoch dazu.

**Comment by danielmarschall** [comment]
Vielen Dank! Bitte beachte, dass beide Arrays ein 2D-Array sind (weil ein Objekt mehrere AltIDs haben kann `$alt_ids[$origin][] = $alternative;`, aber umgekehrt kann eine AltID theoretisch auch auf mehrere Objekte zeigen `$rev_lookup[$alternative][] = $origin;`)

**Comment by wehowski** [comment]
Hi Daniel,
new version: 
* Method getCanonical: Get the one of the Altids with namespace 'oid' https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L208
* https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L104 fetches ALL related IDs, inclusive patched WEID/OID and the id itself.
* Proxy for WHOIS/RDAP to the "canonical" ID https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L32 this maybe should be cached in next version?

The "patches" I added, because the WEID was not in the alt list before and whois/rdap did not work with WEID-alternates.

**Comment by wehowski** [comment]
Although the proxy was added we could/should change the RDAP Plugin?
````
		if (!is_null(OIDplus::getPluginByOid("1.3.6.1.4.1.37553.8.1.8.8.53354196964.641310544"))) { // OIDplusPagePublicAltIds
			$canonical = OIDplusPagePublicAltIds::getCanonicalStatic($query);
			if(false!==$canonical){
			   $query = $canonical;
				$n = explode(':', $query);
				$ns = $n[0];
			}
		}
````

**Comment by danielmarschall** [comment]
Was meinst du mit Proxy?

**Comment by danielmarschall** [comment]
Danke für die Umstellung.
Das Ticket kann nun geschlossen werden.

Geschwindigkeitsproblem wird mit #14 fortgeführt

Die Anbindung im RDAP-Plugin wird in https://github.com/frdl/oidplus-frdlweb-rdap/issues/28 fortgeführt.
