### ISSUE TITLE
Duplicate entry Fehlermeldung

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#11]
On my test system, I constantly get the error message:

`Duplicate entry 'oid:0.4.0.127.0.7.3.2-d8ae57e4-600b-59e2-8499-bfaa4b290602-guid' for key 'id' at query "insert into oobe_alt_ids set id = ?, alt = ?,ns = ?,description = ?, t = ?"
`

It started out of nowhere.

**Comment by wehowski** [comment]
I will investigate it... Did you try to truncate the table after changes? (This did helped me once before)
... there must be an error when checking if the entry `id`,`alt`,`ns` exists already!?!

**Comment by danielmarschall** [comment]
Das Problem ist bei mir dauerhaft reproduzierbar.
Das darf natürlich bei den Produktiv-Systemen niemals auftreten, denn das ist ja ein Showstopper - das System steht komplett und man kann keine OID mehr öffnen.

Ich möchte die Tabelle nicht leeren, da ich damit ja die Reproduktion zerstöre. Wenn du irgendwelche Daten brauchst, sag einfach bescheid.

Der `$info` Array sieht wie folgt aus (`var_export`):

```
array (
  'altIds' => 
  array (
    0 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'E80704007F00070302',
      'ns' => 'aid',
      'description' => 'Application Identifier (ISO/IEC 7816-5)',
    ),
    1 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'd8ae57e4-600b-59e2-8499-bfaa4b290602',
      'ns' => 'guid',
      'description' => 'Name based version 5 / SHA1 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
    2 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'dff3604e-a9bf-3058-94d3-7cd5aebabb2e',
      'ns' => 'guid',
      'description' => 'Name based version 3 / MD5 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
  ),
  'notInDB' => 
  array (
    0 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'E80704007F00070302',
      'ns' => 'aid',
      'description' => 'Application Identifier (ISO/IEC 7816-5)',
    ),
    1 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'd8ae57e4-600b-59e2-8499-bfaa4b290602',
      'ns' => 'guid',
      'description' => 'Name based version 5 / SHA1 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
    2 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'dff3604e-a9bf-3058-94d3-7cd5aebabb2e',
      'ns' => 'guid',
      'description' => 'Name based version 3 / MD5 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
  ),
  'inDB' => 
  array (
    0 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'D276000186F604007F00070302',
      'ns' => 'aid',
      'description' => 'Application Identifier (ISO/IEC 7816-5)',
    ),
    1 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'E80704007F00070302',
      'ns' => 'aid',
      'description' => 'Application Identifier (ISO/IEC 7816-5)',
    ),
    2 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'E8704007F00070302',
      'ns' => 'aid',
      'description' => 'Application Identifier (ISO/IEC 7816-5)',
    ),
    3 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'd8ae57e4-600b-59e2-8499-bfaa4b290602',
      'ns' => 'guid',
      'description' => 'Name based version 5 / SHA1 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
    4 => 
    array (
      'id' => 'oid:0.4.0.127.0.7.3.2',
      'alt' => 'dff3604e-a9bf-3058-94d3-7cd5aebabb2e',
      'ns' => 'guid',
      'description' => 'Name based version 3 / MD5 UUID with namespace UUID_NAMEBASED_NS_OID',
    ),
  ),
)
```

Ich find irgendwie komisch dass nur diese eine OID da drin steht, und so oft?!

Aber wie gesagt, ich würde am liebsten das ganze sehr stark vereinfachen und von der Datenbank wegkommen. Ich befürchte, dass es mit dieser Struktur öfters Probleme geben könnte

**Comment by danielmarschall** [comment]
Datenbank sieht so aus:
![image](https://user-images.githubusercontent.com/28412477/191100768-dc9eaa38-7ab2-4c06-8e58-d1b83842cdfd.png)

**Comment by wehowski** [comment]
Hallo Daniel,
entschuldige bitte die Verspätung!
Sieht aus, als wären die Schlüssel nicht richtig gesetzt!?

> Aber wie gesagt, ich würde am liebsten das ganze sehr stark vereinfachen und von der Datenbank wegkommen. 

Ok, Deine Version scheint konsistenter!

**Comment by danielmarschall** [comment]
> Ok, Deine Version scheint konsistenter!

Freut mich, dass dir meine Idee gefällt. :-) Ich muss nur noch eine Lösung finden, wie man #10 realisieren kann, ohne Geschwindigkeitseinbusen. Es ginge problemlos wenn man Cronjobs verwendet, aber nicht jeder OIDplus-Administrator hat Cronjobs eingerichtet...

**Comment by wehowski** [comment]
Hi Daniel,
> Es ginge problemlos wenn man Cronjobs verwendet, aber nicht jeder OIDplus-Administrator hat Cronjobs eingerichtet...

I have seen in some systems, they offer the admin settings options to either use a "real cronjob" or to fallback to a "fake cronjob". The fake cronjob could be invoked (not more than X times per minute e.g.) via a register_shutdown function or via asynchronous ajax calls by the browser.

**Comment by danielmarschall** [comment]
Da nun keine DB-Tabelle mehr verwendet wird ( #10 ) , geschlossen.
