### ISSUE TITLE
"Hook into" other Plugins plugins (whois, rdap, ....)?

### ISSUE THREAD

**Issue by wehowski** [frdl/oidplus-plugin-alternate-id-tracking#12]
https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L40

* Should we rewrite the plugins (whois, rdap, ....) rather than use the "central" proxy in above init method?
* ---> Event-/Hook -System for the queries? 
* If we do not use this or similar each plugin has to implement a call to getAlternativesForQuery() itself?

**Comment by danielmarschall** [comment]
Ich bin mir nicht sicher, wie wir das im Allgemeinen handhaben sollen.

Auf meinem System hat "aid:D276000097B" die AltID "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185"

Wenn der Benutzer nun in RDAP oder OID-IP eingibt, "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185", was will der Benutzer haben? Will er etwas über die OID wissen, oder über die AID?

Was ist, wenn der Benutzer "aid:D276000097B" eingibt? Will er was über die AID oder etwas über die OID wissen?

Das ist sehr gefährlich, denn am Ende blickt irgendwie niemand mehr durch. Selbst ich hab langsam Probleme, das mit den Alt-IDs zu verstehen.

**Der OID-IP Internet Draft** sieht keine "Umrechnung" der Alt-IDs vor, das heißt, wenn der Anwender "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185" eingibt, dann muss OID-IP versuchen, Informationen für die OID herauszufinden. Er darf keinen Redirect zu "aid" machen! Was er aber dürfte, wäre "so zu tun" als ob die AID in Wirklichkeit die OID 1.3.6.1.4.1.37476.30.9.1675134858.432240185" ist

**Bei RDAP** weiß ich noch nicht, was gewünscht ist und was nicht gewünscht ist.

**Comment by danielmarschall** [comment]
In meiner TODO Liste habe ich folgenden Eintrag:

`should the OID-IP plugin call `OIDplusPagePublicObjects::getAlternativesForQuery` if the Object Could not be found?`

Ich denke, dass jedes Plugin selbst entscheiden sollte, ob es getAlternativesForQuery aufruft oder nicht. Das Alt-ID-Plugin sollte sich da nicht "einmischen"

Wir sollten daher getAlternativesForQuery in das OID-IP und das RDAP Plugin direkt einbauen

**Comment by wehowski** [comment]
> Was ist, wenn der Benutzer "aid:D276000097B" eingibt? Will er was über die AID oder etwas über die OID wissen?

Wenn aid:... als aid: eingetragen ist (*) soll ein query natürlich auf den Eintrag verweisen, wenn es eine alternative ID einer OID ist dann auf den Eintrag der OID.

*) Sorry, ich habe die Sache noch nicht so von dem OIDIP-Protokoll Standpunkt aus betrachtet, meine gewünschte Funktion war zunächst halt die alternativen IDs bzw. queries danach z.B. über RDAP auffindbar zu machen.

**Comment by wehowski** [comment]
> Wir sollten daher getAlternativesForQuery in das OID-IP und das RDAP Plugin direkt einbauen

Ja, sehe ich auch so. Habe ich im  RDAP mal eingebaut: https://github.com/frdl/oidplus-frdlweb-rdap/blob/main/plugins/frdl/publicPages/1276945_rdap/OIDplusRDAP.class.php#L64
 ...

**Comment by danielmarschall** [comment]
**_Bzgl. Thema "Hook into plugins"_**

Diesen Vorschlag möchte ich gerne ablehnen. Die Plugins sollen selbst entscheiden, ob sie bei einem fehlenden Objekt versuchen sollen, ein zu einem AltID umzuleiten.


**_Bzgl. RDAP Plugin_**

Integration mit Alt-IDs wird hier fortgeführt:
https://github.com/frdl/oidplus-frdlweb-rdap/issues/28


**_Bzgl. OID-IP Plugin_**

Ich werde versuchen, `OIDplusPagePublicObjects::getAlternativesForQuery` aufzurufen, wenn ein Objekt nicht gefunden wurde.

Hier kommt ein kleiner "Haken" an der Sache...

Er soll `getAlternativesForQuery` nicht nur aufrufen, wenn das direkt angefragte Objekt nicht gefunden wurde, sondern er soll auch gucken, ob übergeordnete Objekte eine Alt-ID haben...

Beispiel:

oid:1.3.6.1.4.1.37476.30.9  ist im System
oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185  ist die Alt-ID von aid:D276000097B

Wenn ich in OID-IP eingebe "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185.999" , dann soll er "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185" finden, mit distance=1, und den Inhalt von "aid:D276000097B" anzeigen.

Hui, das wird spannend!

**Comment by danielmarschall** [comment]
Da ich leider keinen Bugtracker für OID-IP habe, lasse ich dieses Ticket noch kurz offen, bis ich OID-IP fertig hab.

**Comment by danielmarschall** [comment]
OID-IP berücksichtigt nun die Alt-IDs , siehe OIDplusPagePublicObjects::getAlternativesForQuery() 

Testcase 1:
`weid:pen:SX0-U-9-RPBYBU-75CENT-5`
wird zu
`oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185`
und das wird zu
`aid:D276000097B`
=> Distance 0

Testcase 2:
`weid:pen:SX0-U-9-RPBYBU-75CENT-RR-1`
wird zu
`oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185.999`
und das ist eine Ebene höher als
`oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185`
und das wird zu
`aid:D276000097B`
=> Distance 1
