### ISSUE TITLE
Purpose of getCanonical?

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#13]
Hallo Till,

ich versuche gerade, herauszufinden, wieso der workaround mit RDAP/WHOIS nicht funktioniert. Du schreibst ja `This does not work correctly, due to overload/requests itself???`.

Ich habe folgenden Aufbau:

`aid:D276000097B`

hat die AltID (OIDplus Information Object)

`oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185`

Das funktioniert soweit.

Wenn ich in webwhois.php aber `oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185` eingebe, dann komme ich nicht zu `aid:D276000097B` .

`getAlternativesForQuery('oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185')` ergibt bei mir:

```
array(5) {
  [0]=>
  string(47) "oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185"
  [1]=>
  string(15) "aid:D276000097B"
  [3]=>
  string(41) "guid:ad67303a-fe78-358c-81d6-d242a909ab00"
  [4]=>
  string(41) "guid:09fc8743-00d9-5335-bd2e-02f6d793b047"
  [6]=>
  string(32) "weid:pen:SX0-U-9-RPBYBU-75CENT-5"
}
```

`getCanonical()` ist so programmiert, dass es immer versucht die OID herauszugeben

In `init()` passiert folgendes:

```
                   $canonical = $this->getCanonical($_GET['query']);
                   if(false !== $canonical && $canonical !== $_GET['query']){
```

`$_GET['query']` ist `oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185`
`$canonical` ist `oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185`
... aber ich dachte doch, es soll zu `aid:D276000097B` weitergeleitet werden...??

Also kommt man niemals in den If-Block rein?? Ich versteh nicht was du mit `getCanonical` machen willst?

Weitere Probleme:

- `$_GET['query']` kann bei OID-IP ja auch Auth-Tokens enthalten ( also muss man den Part vor dem ersten `$` nehmen?)

- Natürlich sollte dieser Workaround komplett verschwinden, denn `file_get_contents` wird nicht funktionieren, wenn OIDplus mit Authtype Basic betrieben wird... aber dennoch möchte ich deinen Code verstehen :-)

**Comment by wehowski** [comment]
Hallo Daniel,
> Wenn ich in webwhois.php aber oid:1.3.6.1.4.1.37476.30.9.1675134858.432240185 eingebe, dann komme ich nicht zu aid:D276000097B .

Das hat bei mir funktioniert, als ich den Code in der ->init() method noch nicht auskommentiert hatte (diesen Code mein ich  mit Proxy), ich habe den code auskommentiert, da es Server-Fehler gab, bzw. OIDplus wurde langsam.

> ... aber ich dachte doch, es soll zu aid:D276000097B weitergeleitet werden...??

Jein, es wird in jedem Fall zur "canonical", also OID Version mit dem "proxy" (s.o.) verwiesen. Wenn query schon der kanonische Identifier ist, gibt es kein Grund, bzw. es wäre fatal dann irgendwie "weiterzuleiten" oder so...

getAlternativesForQuery() gibt bei mir ALLE verknüpften IDs, inklusive der Original/UrsprungsId aus.

**Comment by danielmarschall** [comment]
Hallo Till,

Dass das System langsam ist, ist zu erwarten, da `readAll` ja den Cache nicht persistent irgendwo speichert. Das muss natürlich noch gemacht werden.

Wie gesagt, bitte teile mir mit, was der Code in `init()` genau machen soll.

Das OID-IP ist in der Lage, fremde Namespaces zu verwenden, wie z.B. IPv4, AID, GUID etc.
Es muss nichts zu OID "kanonisiert" werden. Ganz im Gegenteil, es darf nicht, sonst funktioniert gar nichts mehr.
Oder versteh ich da was falsch?

**Comment by wehowski** [comment]
> Wie gesagt, bitte teile mir mit, was der Code in init() genau machen soll.

Wenn der Code einkommentiert ist, wird bei https://registry.frdl.de/plugins/viathinksoft/publicPages/100_whois/whois/webwhois.php?query=aid:D276000186E0
die Seite von https://registry.frdl.de/plugins/viathinksoft/publicPages/100_whois/whois/webwhois.php?query=oid%3A2.999 per http geladen und ausgegeben.

**Comment by danielmarschall** [comment]
Das klingt irgendwie gar nicht so gut, wenn ich ehrlich sein soll ^^"

**Comment by wehowski** [comment]
Deshalb habe ich es auskommentiert.
Ich habe das RDAP Plugin angepasst, so das es damit funktioniert: https://registry.frdl.de/plugins/frdl/publicPages/1276945_rdap/rdap/rdap.php?query=aid:D276000186E0

**Comment by danielmarschall** [comment]
Ich denke irgendwie, vielleicht sollten wir das "rumrechnen" in OID-IP und RDAP nicht machen?
Es gibt eben eine Menge verwirrung... dein Beispiel "AID" zu "OID" umrechnen habe ich verstanden, aber ich hatte ja das Gegen-Beispiel "OID" zu "AID" umwandeln... OID-IP kann irgendwie nicht wissen, ob der Benutzer nun in die eine Richtung "denkt" oder in die andere Richtung.
Zu viel Automatik ist manchmal nicht so gut

**Comment by wehowski** [comment]
Es sollen die Einträge auch über ihre alternativen Identifier gefunden werden, und reverse, nix mit "denken" und nix mit "umwandeln".
So war meine Idee!?

**Comment by danielmarschall** [comment]
Wichtig wäre dann aber, dass:
1. OID-IP darf den fremden Namespace nicht zeigen. Er darf die Inhalte zeigen, aber nicht den umgeleiteten Identifier
2. Die Umleitung darf nur passieren, wenn es das angeforderte Objekt nicht direkt gibt (so wie es im Moment mit `?goto=` box implementiert ist)
Hast du eine Idee wie man das am besten löst?

**Comment by danielmarschall** [comment]
(Wird in #12 fortgeführt.)
Die Lösung ist, dass die Plugins RDAP und OID-IP die Funktion `getAlternativesForQuery` nach "eigenem Ermessen" aufrufen und behandeln.
