### ISSUE TITLE
Frdl AltID plugin: Sort alternate-identifier, handle-identifier, and canonical-identifier

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#16]
The latest bundled copy in OIDplus contains a change which sorts alternate-identifier, handle-identifier, and canonical-identifier

Can you please include it here in the upstream? Thanks.

**Comment by wehowski** [comment]
Can you please check if this can be closed with the new version? Thank you!

**Comment by danielmarschall** [comment]
Um was ging's denn hier überhaupt? Ich verstehe meine eigene Anfrage nicht mehr.

**Comment by wehowski** [comment]
Ehrlich gesagt ich weiß nicht? Ging es vielleicht darum das Du dieses Package aus dem Core-Package heraus updaten wolltest?

**Comment by danielmarschall** [comment]
Danke für den Tipp!  Ja, genau das wars. Deswegen hatte ich auch "Upstream" gesagt.

Es geht um SVN Rev 1135. Dies scheint auch mittlerweile genau so drin zustehen, wurde also bereits rein-copy-pasted.
