### ISSUE TITLE
SQL Server nvarchar instead of varchar

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#18]
The ###altids Table for SQL Server has a small problem.

Currently we use data type varchar(255) . However, this is ANSI only, not Unicode. So we cannot add ~poo emojis~ foreign language characters in our identifiers.
![image](https://github.com/frdl/oidplus-plugin-alternate-id-tracking/assets/28412477/84feae76-7ec5-4c71-bc23-53dcb9a6889a)

The correct use would be nvarchar(255), like it is done in the ###objects table too.

Problem: An index in SQL Server must not be longer than 900 bytes.

Therefore, we would need to define the fields like this:
![image](https://github.com/frdl/oidplus-plugin-alternate-id-tracking/assets/28412477/ec375767-bbf6-44c3-8f7a-a5668fde8528)

Yes, there stands 225, not 255.  (4x225 = 900, because a nvarchar is 2 bytes and a varchar is 1 byte)

Pro: Unicode identifiers are possible

Contra: Since ###objects has `nvarchar(255)` and ###altids has `nvarchar(225)`, this could lead to a crash when an "INSERT" query wants to write more data than the field is long.

Should we risk that?  Or change `saveAltIdsForQuery` to ignore identifiers that are longer than 225 chars if the detected SQL Slang is SQL Server?

**Comment by wehowski** [comment]
Mh, I'm not quite sure and do not know much about the different sql dialects, I would just guess we could/should use the same field type for the orig/alt field in the altids table as we use for the id/parent fields in the objects table?

**Comment by danielmarschall** [comment]
But this does not work.

###objects has nvarchar(255)   =  255 Unicode characters

###altids has varchar(255) = 255 ANSI characters.   or nvarchar(225) = 225 Unicode characters.

So we have only two possibilities for SQL Server:

Either:

AltIDs stay ANSI and everything else Unicode  (i.e. identifiers with Unicode characters get lost/corrupt)

or

The AltID table cannot include identifiers which are longer than 225 characters (in case ANYONE is using such extreme long identifiers)


I would choose the second option.  nvarchar(225).  I think the limitation will affect nobody, because I do not think anyone uses identifiers which are longer than 225 characters.
