### ISSUE TITLE
Remove altIds from table if object is deleted

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#19]
Auf das Löschen eines Objekts kannst du mit dem Interface INTF_OID_1_3_6_1_4_1_37476_2_5_2_3_3 reagieren.

Hier bitte folgende Funktionen implementieren:

- afterObjectDelete: Selbsterklärend.
- dann after insert, update usw. : saveAltIdsForQuery aufrufen
- Die anderen Methoden des Interfaces machst du mit leerem Körper.

Für delete: Alternativ könnte man auch Foreign Keys für die DBMS machen. Aber nicht jedes DBMS unterstützt das.

**Comment by wehowski** [comment]
Version 1.0.7 implements ViaThinkSoft\OIDplus\INTF_OID_1_3_6_1_4_1_37476_2_5_2_3_3.

**Comment by wehowski** [comment]
Hallo Daniel,
habe nochmal gefixt: if (!$this->db_table_exists) return; ...
Bitte release so wie es passt und funktioniert!?!

**Comment by danielmarschall** [comment]
Getestet. Funktioniert.
