### ISSUE TITLE
What happens if plugins are updated?

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#2]
Your code re-reads the altIds() as soon as an object is created or updated.

However, if the object type plugin updates (i.e. I have updated the "oid" plugin to include for AID Alt-IDs), then your plugin does not know it.
Theoretically, you plugin would need to re-evaluate its cache everytime, an object type plugin is changed. But how do we achieve this?

**Comment by wehowski** [comment]
Hello Daniel,
I am not sure what you mean exactly?

Yes, maybe we have to prune the cache from time to time?

It "hooks" into before and after delete https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L90
The altIds should be updated automatically by the modifyContent method, when the repository url of the object was visited, maybe it would make sense to add a cronjob or something to update without the object has to be visited in the repository?

**Comment by danielmarschall** [comment]
For example, I changed this code a few days ago:

https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/objectTypes/oid/OIDplusOid.class.php#L488

If I do not access the objects (`modifyContent`), then the altid-tracking-plugin will not know that there is a different altId (due to the updated object type plugin) now.

But I have no idea how to solve the problem in real-time. Pruning a cache every X minues is just a workaround in my opinion

**Comment by danielmarschall** [comment]
Since everything is now calculated on the fly ( #10 ), this problem does not exist anymore.
