### ISSUE TITLE
SQL Delete based on origin only?

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#22]
https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/d21eff0130217794cc0e61785db547986cb5e596/OIDplusPagePublicAltIds.class.php#L54

I am unsure: If an object is deleted, should the DELETE query really also delete the entries where the "alternative = ?" matches? Or just "origin = ?"

Because I think the reverse lookup should always work??

**Comment by wehowski** [comment]
I am not sure if the alternative ever matches?
`Because I think the reverse lookup should always work??`
If an altid is deleted wich should be there, it should be re-added when the orginal is called, or?
Mh?!?

**Comment by danielmarschall** [comment]
I was thinking under which circumstances can an entry with "origin = ?" be created and under which circumstances can an entry with "alternative = ?" be created.

I understand it like this (please correct me if I'm wrong):
- An "origin = ?" entry can be created by accessing or creating an object. And it should therefore only be deleted if the object is deleted. The Registration Authority controls the "origin" entries. They are their objects.
- An "alternative = ?" entry can only be created by the OIDplus system and its plugins. For example, the OID plugin knows how an OID can be transformed in a WEID. Or how an OID is transformed to a UUID. (see also issue #23). So, the Registration Authority cannot do anything here in order to add or remove alternatives. So, deleting an object should not lead to the destruction of alternatives of foreign objects.

**Comment by wehowski** [comment]
I must think about it, but would say, the altIds Table is not because we can not "calculate" the WEIDs/altIds on the fly or in any way, it was introduced to provide a reverse look-up with a reasonable performance!??

**Comment by danielmarschall** [comment]
Yes, it's for fast reverse lookup.

The problem is like this.
 "mac:63-CF-E4-AE-C5-66" is an alt-id of "oid:1.3.6.1.4.1.37553.8.8.2"

Let's assume that "oid:1.3.6.1.4.1.37553.8.8.2" is an object, and  "mac:63-CF-E4-AE-C5-66" is not an object (just an alt-id).

You can create  "mac:63-CF-E4-AE-C5-66" with the Mac-ObjectType-plugin, and then delete this object.
With the current code, it would delete the alt-id of object "oid:1.3.6.1.4.1.37553.8.8.2".

So, when you now enter "mac:63-CF-E4-AE-C5-66" in the GoTo-Box, then it won't be found, because the reverse lookup entry is missing.

**Comment by wehowski** [comment]
Yes, but on the other hand if the object is deleted, the altId relation would refer to an non-existing entry if found?
` with the Mac-ObjectType-plugin`
Then it would be found via the normal- and not the reverse- lookup.
But maybe I am wrong?

**Comment by danielmarschall** [comment]
I didn't test what happens, but it should do the following:


- GoTo "mac:63-CF-E4-AE-C5-66" opens "oid:1.3.6.1.4.1.37553.8.8.2" via reverse-lookup

- User creates object "mac:63-CF-E4-AE-C5-66"  (for whatever reason)

- GoTo "mac:63-CF-E4-AE-C5-66" opens itself via normal lookup

- User deletes object "mac:63-CF-E4-AE-C5-66" 

- GoTo "mac:63-CF-E4-AE-C5-66" should now open "oid:1.3.6.1.4.1.37553.8.8.2" via reverse-lookup again (instead of failing due to the deleted database row)
