### ISSUE TITLE
Delete existing alt-ids on auto-renew?

### ISSUE THREAD

**Issue by danielmarschall** [frdl/oidplus-plugin-alternate-id-tracking#23]
Everytime an object id accessed, it is evaluated by the alt-id-plugin. This is good, because then we automatically get the DB filled, even if no cronjob is running. And search indexes usually crawl everything sooner or later.

https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/d21eff0130217794cc0e61785db547986cb5e596/OIDplusPagePublicAltIds.class.php#L162-L164

However, I think `saveAltIdsForQuery` should not only ADD new identifiers, but also remove identifiers which are not alt-ids anymore? For example, let's say OIDplus Version "X" defines "weid:root:2-RR-3" as an alt-id of "2.999". This would be added to the DB. Now we notice that this alt-id is wrong (or we change our mind, etc.), and change the alt-id to "weid:root:2-RR-2". But the old/wrong alt-id is still there.

Therefore, I suggest that `saveAltIdsForQuery` shall do a `DELETE from ###altids where origin = ?` before adding the new objects. What do you think?

**Comment by wehowski** [comment]
I would do the DELETE only in case of changing the DB (the *object hooks), for seperation of concerns and avoiding to calculate "all at once in one request" again. And: If you "change" an OID, its ID, it would be more like a DELETE and INSERT a new one than a change, because it is a new ID the old altIds can be deleted/recalculated rather than to be changed?

**Comment by danielmarschall** [comment]
> I would do the DELETE only in case of changing the DB (the *object hooks), for seperation of concerns and avoiding to calculate "all at once in one request" again

If a new version of OIDplus or a plugin is installed, then all objects need to be rechecked eventually. (For example, just a few days ago, I changed the definition of an AID scheme, so their altids changed). We cannot wait until the RA changes an object. Some objects might never be edited by the RA again.

I think the performance is not a problem. Currently we call `saveAltIdsForQuery` once in `init` of every PHP processing, and one `saveAltIdsForQuery` in case any modify object hook is called. These 1-2 calls don't impact performance much.

Also, these 1-2 calls won't change. The only thing that changes is that `"n-times" SELECT + "n-times" INSERT` is changed to `1 DELETE + "n-times" INSERT`, so even the amount of database operations even become less - **_improving_** the performance.
Though, there need to be a few details to consider:
- By using DELETE + INSERT, we need to make sure that the array that fills `alternatives` is unique using `array_unique`.
- This operation should be in a transaction (but not all DBMS support transaction), otherwise if 2 calls happen at the same time, then there could be an INSERT primary key collission (though this risk is also existing in the current version where we do "SELECT + INSERT", since these two operations together are not atomic.

> And: If you "change" an OID, its ID, it would be more like a DELETE and INSERT a new one than a change, because it is a new ID the old altIds can be deleted/recalculated rather than to be changed?

Currently, in OIDplus, you cannot change an OID. And even if you could do it (... the "move OID" feature is still in my mind ...), then the object hook "delete" and "insert" would be called.

**Comment by wehowski** [comment]
`If a new version of OIDplus or a plugin is installed, then all objects need to be rechecked eventually. (For example, just a few days ago, I changed the definition of an AID scheme, so their altids changed). We cannot wait until the RA changes an object. Some objects might never be edited by the RA again.`
Maybe it yould make sense, in case of an OIDplus update, to TRUNCATE the altIds table?
However, if there is no perfomance impact but improvement, as you say, then let's just do it!?!
(Can you please change it to make sure the delete is implemented in the way you want?)

**Comment by danielmarschall** [comment]
Sure, I can change it.
I just wonder what we should do to avoid a primary key conflict crash?
"SELECT + INSERT" as well as "DELETE + INSERT" can have a "race-condition",
if two clients call the service at exactly the same second.
