### ISSUE TITLE
AltId Object Page (Public Page Entry)

### ISSUE THREAD

**Issue by wehowski** [frdl/oidplus-plugin-alternate-id-tracking#8]
I think this maybe a "core" question, not related to the plugin(s) directly?

"Es wäre gut wenn bei ?goto= wie beim RDAP auf den assoziierten Eintrag verwiesen würde (statt 404 Error)

Beispiel:

aid:D276000186E0 ist im RDAP zu finden https://registry.frdl.de/plugins/frdl/publicPages/1276945_rdap/rdap/rdap.php?query=aid:D276000186E0

wirft aber hier einen 404 not found https://registry.frdl.de/?goto=aid%3AD276000186E0

mit assoziierten Einträgen meine ich in diesem Fall oid:2.999"

**Comment by danielmarschall** [comment]
Gerne können wir auch Kern-Fragen für OIDplus beantworten :-)

Ok, ich glaube ich verstehe was du meinst ....
Lass mich es nochmal anders ausdrücken:

Das RDAP-Plugin unterstützt deine Alt-ID-Tabelle und ist deswegen in der Lage, die Alt-ID von aid:D276000186E0 umzuwandeln in die OID 2.999 , und deswegen bekomme ich Einträge für oid:2.999 angezeigt.

In ?goto= funktioniert das nicht, denn das Objekt aid:D276000186E0 gibt es bei dir nicht.

Was du beschreibst könnte man eventuell mit `OIDplus::prefilterQuery()` lösen. Im Moment fragt prefilterQuery aber nur die Plugins der Klasse ObjectType ab. Vielleicht sollte man es auf die Klasse der PagePlugins erweitern?

Die Idee ist, dass dein Plugin die Anfrage aid:D276000186E0 umschreibt zu oid:2.999 , in dem in der Alt-Id-Cache-Tabelle gesucht wird.
Aber Achtung: Was ist wenn es das Objekt aid:D276000186E0 bereits gibt? Dann sollte keinesfalls zu oid:2.999 umgeleitet werden!

Daher die Idee, ob man das Feature "prefilter query" und das Feature "handle 404" nicht irgendwie zusammenlegt, sodass ich sage, "**erlaube dem Plugin die Query umzuschreiben, wenn es das Objekt (nativ) nicht gibt**" ?

**Comment by danielmarschall** [comment]
PrefilterQuery ist der falsche weg, denn das Präfiltern findet ganz am Anfang statt und prüft nicht nach den Objekten.

Irgendwie müsste man hier was ändern:
https://github.com/danielmarschall/oidplus/blob/master/plugins/viathinksoft/publicPages/000_objects/OIDplusPagePublicObjects.class.php#L535

Das PagePlugin OIDplusPagePublicObjects könnte bei einem Fehlschlag per Feature-OID die anderen Pages fragen, ob sie wissen, wie man das Objekt anders nennen könnte, und dann müsste er die Prozedur in OIDplusPagePublicObjects nochmal beginnen (Achtung vor Endlos-Iteration!)

**Comment by danielmarschall** [comment]
OIDplus-Version 951 erlaubt es nun, dass bei einem Nicht-Existieren von Plugins das System (genauergesagt das Objects-Plugin) andere Plugins bittet, alternativ-Namen zu nennen.

Dann kannst du folgenden Code einbauen bzw. vervollständigen:

```
        public function getAlternativesForQuery($id) {
                // Interface 1.3.6.1.4.1.37476.2.5.2.3.7
                // TODO: implement
                $alternatives = array();
                if ($id == 'oid:1.3.6.1.4.1.37476.30.9.1675134858.530480824') {
                        $alternatives[] = 'aid:D276000098';
                }
                return $alternatives;
        }

        public function implementsFeature($id) {
                if (strtolower($id) == '1.3.6.1.4.1.37476.2.5.2.3.7') return true; // getAlternativesForQuery
                return false;
        }

```

**Comment by wehowski** [comment]
Hi Daniel,
I implemented the method, but still got 404 not found on alternate ids.
https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L49

**Comment by danielmarschall** [comment]
Hello Till,
do you have some more details / test cases? Which values go in and which values go out? Stacktrace?
Yesterday, I successfully tested ?goto=oid:1.3.6.1.4.1.37476.30.9.1675134858.530480824 showing aid:D276000098

**Comment by danielmarschall** [comment]
Es muss an deiner Implementierung liegen. Bei mir geht alles.

```
public function getAlternativesForQuery($id) {

// Interface 1.3.6.1.4.1.37476.2.5.2.3.7
$alternatives = [];
if ($id == 'oid:1.3.6.1.4.1.37476.30.9.1675134858.1374707849') { // OIDplus Information OID (AltID, not in DB)
        $alternatives[] = 'gs1:0012000'; // Pepsi GS1 ("original, existing in DB")
}
return $alternatives;
}
```
Hast du auch die neuste Version von OIDplus installiert?

**Comment by wehowski** [comment]
Hallo Daniel,
vielleicht liegt irgendein Missverständnis vor.
Beispiel: 
Im RDAP ist der Eintrag über die AltId auffindbar:
https://registry.frdl.de/plugins/frdl/publicPages/1276945_rdap/rdap/rdap.php?query=guid:31cb1efa-18c4-3d19-89ba-df6a74ddbd1d
Meine Erwartung wäre jetzt das das auch mit der "normalen" Repositoryseite funktioniert, also:
https://registry.frdl.de/?goto=guid%3A31cb1efa-18c4-3d19-89ba-df6a74ddbd1d
Funzt aber nicht - 404.

Ja, es ist die aktuelle Version installiert, implentiert ist diese Version f5fa17a19e9dc654eb80ed10027a87ee4d6247e8  https://github.com/frdl/oidplus-plugin-alternate-id-tracking/blob/main/plugins/frdl/publicPages/altids/OIDplusPagePublicAltIds.class.php#L49

**Comment by wehowski** [comment]
Sorry KEIN 404: Invalid OID guid:31cb1efa-18c4-3d19-89ba-df6a74ddbd1d

**Comment by danielmarschall** [comment]
Ich hab im Moment große Probleme das zu reproduzieren :-(
Hast du einen Stacktrace oder irgendwas?

**Comment by danielmarschall** [comment]
Ich glaube dass ich Verständnisprobleme habe, wie dein Code gemeint ist...

Ich schreibe mal wie ich es verstehe:

In meiner Datenbank (Tabelle "objects") gibt es `aid:D2760000`.
Eine AID kann man auch als OID schreiben (`OIDplusAid::getAltIds()`) z.B. `oid:1.3.6.1.4.1.37476.30.9.1675134858.1040608017`.

Wenn ich nun `?goto=oid:1.3.6.1.4.1.37476.30.9.1675134858.1040608017` eingebe, dann bekomme ich normalerweise 404, weil es das in meiner "objects" Tabelle nicht gibt.

Mit dem Reverse-Alt-ID bekomme ich jetzt dann aber das Ergebnis `aid:D2760000` .

Das hat mit meinem Code funktioniert. Mit deinem Code funktioniert es im Moment bei mir gar nicht.

**Comment by danielmarschall** [comment]
Bug "Invalid OID" war ein Problem im system. Ist nun gefixt in SVN Rev 953

plugins/viathinksoft/publicPages/000_objects/OIDplusPagePublicObjects.class.php

```
                $row = null;
                $matches_any_registered_type = false;
                foreach (OIDplus::getEnabledObjectTypes() as $ot) {
-                       if ($obj = $ot::parse($id)) {
+                       try {
+                               $obj = OIDplusObject::parse($id);
+                       } catch (Exception $e) {
+                               $obj = null;
+                       }
+                       if (!is_null($obj)) {
                                $matches_any_registered_type = true;
                                if ($obj->isRoot()) {
```

Nachdem ich den Patch angewendet habe, kommt "Invalid OID" nicht mehr. Aber das reverse Alt-ID, so wie ich es gestern programmiert habe, funktioniert trotzdem nicht mit deinem `getAlternativesForQuery ` Code. Ich glaub deine Implementierung von `getAltIdsInfo` soll irgendwas anderes machen? Ich versteh die Funktion des Codes leider nicht.

**Comment by danielmarschall** [comment]
Habe dein System aktualisiert. "Invalid OID" ist jetzt behoben.
Jetzt kommt 404: https://registry.frdl.de/?goto=guid%3A31cb1efa-18c4-3d19-89ba-df6a74ddbd1d

**Comment by danielmarschall** [comment]
Folgender Code (basierend auf #10 ) funktioniert (so wie ich die Funktionalität verstehe):

```
        public static function test() {
                $alt_ids = array();
                $rev_lookup = array();

                $res = OIDplus::db()->query("select id from ###objects");
                while ($row = $res->fetch_array()) {
                        $obj = OIDplusObject::parse($row['id']);
                        if (!$obj) continue; // e.g. if plugin is disabled
                        $ary = $obj->getAltIds();
                        foreach ($ary as $a) {
                                $origin = $obj->nodeId(true);
                                $alternative = $a->getNamespace() . ':' . $a->getId();

                                if (!isset($alt_ids[$origin])) $alt_ids[$origin] = array();
                                $alt_ids[$origin][] = $alternative;

                                if (!isset($rev_lookup[$alternative])) $rev_lookup[$alternative] = array();
                                $rev_lookup[$alternative][] = $origin;
                        }
                }
                return array($alt_ids, $rev_lookup);
        }

       public function getAlternativesForQuery($id) {
                list($alt_ids, $rev_lookup) = self::test();
                if (!isset($rev_lookup[$id])) return array();
                return $rev_lookup[$id];
        }

```

Natürlich extrem langsam, nur zum Testen!

**Comment by wehowski** [comment]
Sorry, ich komm nicht so schnell mit.
Mein Code/Plugin ermittelt die AltIds und schreibt sie wenn noch nicht vorhanden in die DB-Tabelle.

Ziel ist, dass unter https://registry.frdl.de/?goto=guid%3A31cb1efa-18c4-3d19-89ba-df6a74ddbd1d
der Eintrag erscheint: https://registry.frdl.de/?goto=oid%3A2.999

**Comment by wehowski** [comment]
$res = OIDplus::db()->query("select id from ###objects");
Das fetcht und prüft doch ALLE Einträge? Kann man das nicht etwas optimieren für große Datenbanken? Ich meine die ALtIds sind ja schon in der alt_ids Tabelle, warum nochmal über das ganze Repository iterieren?
Jedenfalls: getAlternativesForQuery wird bei  mir nun gar nicht mehr aufgerufen irgendwie?

**Comment by danielmarschall** [comment]
Ich iteriere über alle Einträge, um die Datenbank zu ersetzen, siehe #10 .
Muss natürlich noch optimiert und gecached werden. Mein Code oben ist langsam und nur zum testen da.
Das Erzeugen der Tabelle ohne Datenbankcache löst die Probleme #1 und #2

**Comment by danielmarschall** [comment]
Bei meinem System funktioniert es einwandfrei:

https://oidplus.viathinksoft.com/oidplus_dev/?goto=guid%3A31cb1efa-18c4-3d19-89ba-df6a74ddbd1d

Ich habe OIDplus Version 954 instaliert, sowie das Plugin [f5fa17a](https://github.com/frdl/oidplus-plugin-alternate-id-tracking/commit/f5fa17a19e9dc654eb80ed10027a87ee4d6247e8) und meinen (langsamen) Testcode von oben. Mit deinem Originalcode funktioniert es nicht im Moment, aber ich weiß nicht warum, da ich Probleme habe, den Code zu verstehen.

Wenn ich den `test()` Code bei dir einbaue, geht auch alles:
https://registry.frdl.de/?goto=guid%3A31cb1efa-18c4-3d19-89ba-df6a74ddbd1d

Also, es liegt an deinem ursprünglichen Code von `getAlternativesForQuery`, der macht irgendwas falsch

**Comment by wehowski** [comment]
Geht allerdings nur wenn der Object Type freigeschaltet ist!
Wenn ich "aid" deaktiviere funktioniert auch https://registry.frdl.de/?goto=aid%3AD276000186F62B0601040182A531 nicht mehr!

**Comment by danielmarschall** [comment]
Das ist komisch.

**_Beabsichtigt_** in meiner Funktion `test()` ist meinerseits folgendes
- `$alt_ids` enthält **keine** gesperrten Objekttypen. Denn bei einem gesperrten Objekt-Typ soll das Programm sich so verhalten, als wäre der Plugin-Ordner komplett gelöscht.
- `$rev_lookup` hingegen sollte die gesperrten Objekttypen enthalten, denn beispielsweise das OID-Plugin zeigt AID-AltIDs, obwohl AID gar nicht freigeschaltet ist. Folglich sollte ein `?goto=aid:` funktionieren

Ich versuche mal eine Reproduktion

**Comment by danielmarschall** [comment]
Reproduktion bei mir erfolgreich. Ich versuche das Problem zu finden.

**Comment by danielmarschall** [comment]
Ok, das Problem lag im system code und ist nun behoben in SVN Rev 955 bzw. https://github.com/danielmarschall/oidplus/commit/4e509efff7d9c2e1179191ec50aba6ec11b0375d

Jetzt funktioniert ein Reverse-Lookup auch , wenn der ursprüngliche Objekt-Typ deaktiviert ist

**Comment by danielmarschall** [comment]
Da "reverse alt id search" nun in OIDplus (mittels `getAlternativesForQuery` Feature OID) eingebaut ist, schließe ich dieses Thema.
Falls noch ein Bug drin ist, bitte nochmal neu aufmachen.

Die Entscheidung wie wir `getAlternativesForQuery` implementieren, mittels Datenbanktabelle oder on-the-fly etc., führen wir in #10 fort.

Vielen Dank für deine Vorschläge und Bugreports. Das bedeutet mir sehr viel!
